apiVersion: config.kubernetes.io/v1alpha1
kind: ResourceList
items:
- apiVersion: kpt.seek.com/v1alpha1
  kind: ClusterPackages
  metadata:
    name: cluster-packages
  spec:
    baseDir: target/packages
    packages:
    - name: cert-manager
      git:
        repo: git@github.com:SEEK-Jobs/gantry-packages.git
        directory: test
        ref: b5641f5a7dac5baa6598baa165d93608aeac24ff
    variables:
    - name: account-id
      value: 00000
    - name: region
      value: ap-southeast-3
    - name: region-short
      value: apse3
    - name: cluster
      value: production-a
    - name: environment
      value: production
    - name: oidc-provider-id
      value: ABCDEFG
    - name: internal-domain-name
      value: ap-southeast-3.production.internal.seek.com
    - name: external-domain-name
      value: ap-southeast-3.production.external.seek.com
    - name: internal-hosted-zone-id
      value: INT001
    - name: external-hosted-zone-id
      value: EXT001
