apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
  namespace: example
spec:
  replicas: 2
  selector:
    matchLabels:
      name: example
  template:
    metadata:
      annotations:
        kpt.seek.com/hash-dependency/config-map: ConfigMap/config-map
    spec:
      containers:
        - name: httpbin
          image: kennethreitz/httpbin
