apiVersion: config.kubernetes.io/v1alpha1
kind: ResourceList
items:
- apiVersion: kpt.seek.com/v1alpha1
  kind: ClusterPackages
  metadata:
    name: cluster-packages
  spec:
    baseDir: target/packages
    packages:
    - name: test
      git:
        repo: git@github.com:SEEK-Jobs/gantry-packages.git
        directory: test
        ref: 5fc702d3dd0f46509283cb0bcc4a3327d1ee8b1d
    variables:
    - name: account-id
      value: 00000
    - name: region
      value: ap-southeast-3
    - name: region-short
      value: apse3
    - name: cluster
      value: production-a
    - name: environment
      value: production
    - name: oidc-provider-id
      value: ABCDEFG
    - name: internal-domain-name
      value: ap-southeast-3.production.internal.seek.com
    - name: external-domain-name
      value: ap-southeast-3.production.external.seek.com
    - name: internal-hosted-zone-id
      value: INT001
    - name: external-hosted-zone-id
      value: EXT001
    - name: irsa-policy
      value: |-
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "Federated": 'arn:aws:iam::{{value "account-id"}}:oidc-provider/oidc.eks.{{value "region"}}.amazonaws.com/id/{{value "oidc-provider-id"}}'
              },
              "Action": "sts:AssumeRoleWithWebIdentity",
              "Condition": {
                "StringEquals": {
                  "oidc.eks.{{value "region"}}.amazonaws.com/id/{{value "oidc-provider-id"}}:sub": "system:serviceaccount:{{args 0}}:{{if eq nargs 1}}{{args 0}}{{else}}{{args 1}}{{end}}"
                }
              }
            }
          ]
        }
