name: Build functions, publish to DockerHub
on:
  push:
    branches:
    - master
    tags:
    - 'v/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.16'
    - name: Log into registry
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin <<< "${{
        secrets.DOCKER_API_KEY }}"
    - name: Push image
      run: |
        if [[ "${{ github.ref }}" =~ ^refs/tags/v/(.*) ]] ; then
          VERSION="${BASH_REMATCH[1]}"
        elif [[ "${{ github.ref }}" =~ ^refs/heads/master ]] ; then
          VERSION="latest"
        else
          VERSION="unknown"
        fi

        make publish-all VERSION=${VERSION}
