name: Build functions, publish to Dockerhub

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14'
      - name: Lint
        run:  sudo snap install shfmt && make lint
      - name: Run tests
        run: make test
