apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
  namespace: my-namespace # {"$kpt-set":"namespace"}
spec:
  replicas: 5 # {"$kpt-set":"replicas"}
  selector:
    matchLabels:
      name: deploy
  template:
    metadata:
      labels:
        name: deploy
    spec:
      containers:
      - name: httpbin
        image: kennethreitz/httpbin:latest
        env:
        - name: REGION
          value: ap-southeast-2 # {"$kpt-set":"region"}
        - name: ACCOUNT_ID
          value: "12345678" # {"$kpt-set":"account-id"}
